In [7]:
from tensorflow.keras.models import load_model
import tensorflow as tf


In [ ]:
import os
from collections import Counter
train_dir = "../data/processed/pokemon_images_255_class"
counts = Counter([d for d in os.listdir(train_dir) if os.path.isdir(os.path.join(train_dir, d))])
print(counts)

Counter({'Abra': 1, 'Aerodactyl': 1, 'Aipom': 1, 'Alakazam': 1, 'Ampharos': 1, 'Arbok': 1, 'Arcanine': 1, 'Ariados': 1, 'Articuno': 1, 'Azumarill': 1, 'Bagon': 1, 'Barboach': 1, 'Bayleef': 1, 'Beedrill': 1, 'Bellossom': 1, 'Bellsprout': 1, 'Blastoise': 1, 'Blissey': 1, 'Bulbasaur': 1, 'Butterfree': 1, 'Caterpie': 1, 'Celebi': 1, 'Chansey': 1, 'Charizard': 1, 'Charmander': 1, 'Charmeleon': 1, 'Chikorita': 1, 'Chinchou': 1, 'Clefable': 1, 'Clefairy': 1, 'Cleffa': 1, 'Cloyster': 1, 'Corsola': 1, 'Crobat': 1, 'Croconaw': 1, 'Cubone': 1, 'Cyndaquil': 1, 'Delibird': 1, 'Deoxys': 1, 'Dewgong': 1, 'Diglett': 1, 'Ditto': 1, 'Dodrio': 1, 'Doduo': 1, 'Donphan': 1, 'Dragonair': 1, 'Dragonite': 1, 'Dratini': 1, 'Drowzee': 1, 'Dugtrio': 1, 'Dunsparce': 1, 'Eevee': 1, 'Ekans': 1, 'Electabuzz': 1, 'Electrode': 1, 'Elekid': 1, 'Entei': 1, 'Espeon': 1, 'Exeggcute': 1, 'Exeggutor': 1, 'Fearow': 1, 'Feraligatr': 1, 'Flaaffy': 1, 'Flareon': 1, 'Forretress': 1, 'Furret': 1, 'Gastly': 1, 'Gengar': 1, 'Geodud

In [2]:
type(counts)

collections.Counter

In [3]:
lst=[]
for i in counts:
    if counts[i]>1:
        lst.append(i)
        

In [4]:
lst

[]

In [2]:
from tensorflow.keras.models import load_model

# Path to your saved model file
model = load_model(r'..\backend\models\pokemon_resnet_model.keras')


In [5]:
test_dir=r"..\data\processed\pokemon_images_255_test"


In [8]:
test_ds = tf.keras.utils.image_dataset_from_directory(
    test_dir,
    labels='inferred',         # or 'categorical' for one-hot
    label_mode='categorical',  # or 'int'
    batch_size=32,
    image_size=(128, 128),
    shuffle=False
)

Found 506 files belonging to 253 classes.


In [9]:
import numpy as np
y_true = []
y_pred = []

for images, labels in test_ds:
    preds = model.predict(images)
    y_true.extend(np.argmax(labels.numpy(), axis=1))
    y_pred.extend(np.argmax(preds, axis=1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 718ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 724ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 804ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 963ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 980ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 794ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 974ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 847ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 801ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 763ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 697ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 766ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step


In [12]:
len(y_pred)

506

In [13]:
len(y_true)

506

In [15]:
from sklearn.metrics import classification_report, confusion_matrix, precision_score, recall_score

In [ ]:
import json
with open("class_names.json", "r") as f:
    class_names = json.load(f)

In [17]:
print(classification_report(y_true, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.40      1.00      0.57         2
           2       1.00      0.50      0.67         2
           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00         2
           5       1.00      1.00      1.00         2
           6       1.00      1.00      1.00         2
           7       1.00      0.50      0.67         2
           8       0.50      1.00      0.67         2
           9       1.00      1.00      1.00         2
          10       0.00      0.00      0.00         2
          11       0.00      0.00      0.00         2
          12       1.00      0.50      0.67         2
          13       0.40      1.00      0.57         2
          14       1.00      0.50      0.67         2
          15       1.00      0.50      0.67         2
          16       0.00      0.00      0.00         2
          17       0.29    

e:\Anaconda\envs\py3.10\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
e:\Anaconda\envs\py3.10\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
e:\Anaconda\envs\py3.10\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
e:\Anaconda\envs\py3.10\lib\site-packag

In [18]:
cm = confusion_matrix(y_true, y_pred)
print(cm)

[[0 0 0 ... 0 0 0]
 [0 2 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [19]:

import tensorflow as tf

train_dir = "../data/processed/pokemon_images_255_class"  # or your actual training directory
img_height, img_width = 128, 128

# Use batch_size=1 and shuffle=False for speed and consistency
ds = tf.keras.utils.image_dataset_from_directory(
    train_dir,
    labels='inferred',
    label_mode='categorical',
    batch_size=1,
    image_size=(img_height, img_width),
    shuffle=False
)
class_names = ds.class_names
print(class_names)

Found 14116 files belonging to 255 classes.
['Abra', 'Aerodactyl', 'Aipom', 'Alakazam', 'Ampharos', 'Arbok', 'Arcanine', 'Ariados', 'Articuno', 'Azumarill', 'Bagon', 'Barboach', 'Bayleef', 'Beedrill', 'Bellossom', 'Bellsprout', 'Blastoise', 'Blissey', 'Bulbasaur', 'Butterfree', 'Caterpie', 'Celebi', 'Chansey', 'Charizard', 'Charmander', 'Charmeleon', 'Chikorita', 'Chinchou', 'Clefable', 'Clefairy', 'Cleffa', 'Cloyster', 'Corsola', 'Crobat', 'Croconaw', 'Cubone', 'Cyndaquil', 'Delibird', 'Deoxys', 'Dewgong', 'Diglett', 'Ditto', 'Dodrio', 'Doduo', 'Donphan', 'Dragonair', 'Dragonite', 'Dratini', 'Drowzee', 'Dugtrio', 'Dunsparce', 'Eevee', 'Ekans', 'Electabuzz', 'Electrode', 'Elekid', 'Entei', 'Espeon', 'Exeggcute', 'Exeggutor', 'Fearow', 'Feraligatr', 'Flaaffy', 'Flareon', 'Forretress', 'Furret', 'Gastly', 'Gengar', 'Geodude', 'Girafarig', 'Glalie', 'Gligar', 'Gloom', 'Golbat', 'Goldeen', 'Golduck', 'Golem', 'Granbull', 'Graveler', 'Grimer', 'Growlithe', 'Gyarados', 'Haunter', 'Heracross'

In [20]:
import json
with open("class_names.json", "w") as f:
    json.dump(class_names, f)

In [21]:
import json
with open("class_names.json", "r") as f:
    class_names = json.load(f)

In [22]:
print(classification_report(y_true, y_pred, target_names=class_names))

              precision    recall  f1-score   support

        Abra       0.00      0.00      0.00         2
  Aerodactyl       0.40      1.00      0.57         2
       Aipom       1.00      0.50      0.67         2
    Alakazam       0.00      0.00      0.00         2
    Ampharos       0.00      0.00      0.00         2
       Arbok       1.00      1.00      1.00         2
    Arcanine       1.00      1.00      1.00         2
     Ariados       1.00      0.50      0.67         2
    Articuno       0.50      1.00      0.67         2
   Azumarill       1.00      1.00      1.00         2
       Bagon       0.00      0.00      0.00         2
    Barboach       0.00      0.00      0.00         2
     Bayleef       1.00      0.50      0.67         2
    Beedrill       0.40      1.00      0.57         2
   Bellossom       1.00      0.50      0.67         2
  Bellsprout       1.00      0.50      0.67         2
   Blastoise       0.00      0.00      0.00         2
     Blissey       0.29    

e:\Anaconda\envs\py3.10\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
e:\Anaconda\envs\py3.10\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
e:\Anaconda\envs\py3.10\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
e:\Anaconda\envs\py3.10\lib\site-packag

In [23]:
macro_precision = precision_score(y_true, y_pred, average='macro')
macro_recall = recall_score(y_true, y_pred, average='macro')
micro_precision = precision_score(y_true, y_pred, average='micro')
micro_recall = recall_score(y_true, y_pred, average='micro')

print(f"Macro Precision: {macro_precision:.4f}, Macro Recall: {macro_recall:.4f}")
print(f"Micro Precision: {micro_precision:.4f}, Micro Recall: {micro_recall:.4f}")

Macro Precision: 0.0709, Macro Recall: 0.0765
Micro Precision: 0.0771, Micro Recall: 0.0771


e:\Anaconda\envs\py3.10\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
e:\Anaconda\envs\py3.10\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


In [42]:
from PIL import Image
import numpy as np

img_path = r"..\data\processed\pokemon_images_255_test\Pikachu\Pikachu.png"  # Change to your image path
img_height, img_width = 128, 128  # Use the same size as during training

# Load and preprocess the image
image = Image.open(img_path).convert("RGB").resize((img_height, img_width))
img_array = np.array(image)  # Do NOT divide by 255 if you used Rescaling layer
img_array = np.expand_dims(img_array, axis=0)  # Add batch dimension

In [43]:
pred = model.predict(img_array)
predicted_index = np.argmax(pred)
predicted_species = class_names[predicted_index]
print(f"Predicted species: {predicted_species}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 213ms/step
Predicted species: Pikachu


In [39]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ resnet50 (Functional)           │ (None, 4, 4, 2048)     │    23,587,712 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling2d        │ (None, 2048)           │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │       262,272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 255)            │        32,895 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 42,335,871 (161.50 MB)

 Trainable params: 9,226,495 (35.20 MB)

 Non-trainable params: 14,656,384 (55.91 MB)

 Optimizer params: 18,452,992 (70.39 MB)